
package ViewCustomerData;


import CustomerManagement.*;
import Home_Page.Home_Tab;
import ViewCustomerData.viewCustList;
import ViewCustomerData.viewCustUsage;
import ViewCustomerData.viewCustBilling;
import ViewCustomerData.viewCustMeter;
import ViewCustomerData.viewCustTariff;
import ViewCustomerData.viewCustPayment;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
 

public class viewCustBilling extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    Color defaultcolor, clickedcolor, white; 
    public viewCustBilling() {
        setUndecorated(true); 
        
        initComponents();
        Con();
        GraphicsDevice gd = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
        gd.setFullScreenWindow(this); // Set the JFrame to full screen
        
        defaultcolor = new Color(0,0,102);
        clickedcolor = new Color(0,102,204);
        white = new Color (255,255,255);
        
        
    }
        Connection con; //= null;
        PreparedStatement ps;// = null;
        ResultSet rs;// = null;Connection con; //= null;
        
public void Con() {
    try {
        // Establish connection
        Class.forName("com.mysql.cj.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/2104_wrs", "root", "");
        System.out.println("Connection Successful");

        // Prepare the SQL query to select all records from 'billing' table
       ps = con.prepareStatement("SELECT * FROM billing");

        // Execute the query
        rs = ps.executeQuery();

        // Create a DefaultTableModel for the JTable
        DefaultTableModel model = new DefaultTableModel();

        // Define the column names
        model.addColumn("BILLINGID");
        model.addColumn("BILLING_DATE");
        model.addColumn("TOTAL_AMOUNT");
        model.addColumn("PAYMENT_STATUS");

        // Process the result set and add rows to the table model
        while (rs.next()) {
            // Get data from the result set
            String billingID = rs.getString("billID");
            String billingDate = rs.getString("billingDate");
            String totalAmount = rs.getString("totalAmount");
            String paymentStatus = rs.getString("paymentStatus");

            // Add the row to the model
            model.addRow(new Object[]{billingID, billingDate, totalAmount, paymentStatus});
        }

        // Set the model to your JTable (assuming your JTable is named billingTable)
        billingTable.setModel(model);

        // Optionally show a success message
        // JOptionPane.showMessageDialog(this, "Billing data displayed successfully!");

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "An error occurred while fetching billing data: " + ex.getMessage());
        ex.printStackTrace(); // or use a logger if needed
    } finally {
        // Close resources to prevent memory leaks
        try {
            if (rs != null) rs.close();
            if (ps != null) ps.close();
            if (con != null) con.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panHome = new javax.swing.JPanel();
        lblHome = new javax.swing.JLabel();
        panCustomer = new javax.swing.JPanel();
        lblCustomer = new javax.swing.JLabel();
        panView = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lblView = new javax.swing.JLabel();
        panList = new javax.swing.JPanel();
        lblList = new javax.swing.JLabel();
        panUsage = new javax.swing.JPanel();
        lblUsage = new javax.swing.JLabel();
        panBilling = new javax.swing.JPanel();
        lblBilling = new javax.swing.JLabel();
        panAdmin = new javax.swing.JPanel();
        lblAdmin = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        panTariff = new javax.swing.JPanel();
        lblTarrif = new javax.swing.JLabel();
        panPayment = new javax.swing.JPanel();
        lblPayment = new javax.swing.JLabel();
        panMeter = new javax.swing.JPanel();
        lblMeter = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        billingTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(1366, 70));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/image-80x80.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 68, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/image-100x50.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 90, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Water Retailing System");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 170, 20));

        jButton1.setBackground(new java.awt.Color(0, 102, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-x-40.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 60));

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/[removal.ai]_48484233-07f1-4ece-aedf-79c0f0f87e72-untitled-200-x-200-px.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setText("MAIN MENU");

        panHome.setBackground(new java.awt.Color(0, 0, 102));
        panHome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblHome.setBackground(new java.awt.Color(255, 255, 255));
        lblHome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHome.setForeground(new java.awt.Color(255, 255, 255));
        lblHome.setText("                     HOME");
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblHomeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblHomeMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout panHomeLayout = new javax.swing.GroupLayout(panHome);
        panHome.setLayout(panHomeLayout);
        panHomeLayout.setHorizontalGroup(
            panHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panHomeLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblHome, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panHomeLayout.setVerticalGroup(
            panHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHome, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        panCustomer.setBackground(new java.awt.Color(0, 0, 102));
        panCustomer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblCustomer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCustomer.setForeground(new java.awt.Color(255, 255, 255));
        lblCustomer.setText("CUSTOMER MANAGEMENT");
        lblCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCustomerMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCustomerMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblCustomerMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout panCustomerLayout = new javax.swing.GroupLayout(panCustomer);
        panCustomer.setLayout(panCustomerLayout);
        panCustomerLayout.setHorizontalGroup(
            panCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCustomerLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(lblCustomer)
                .addGap(30, 30, 30))
        );
        panCustomerLayout.setVerticalGroup(
            panCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panView.setBackground(new java.awt.Color(0, 0, 102));
        panView.setForeground(new java.awt.Color(255, 255, 255));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-view-23.png"))); // NOI18N

        lblView.setBackground(new java.awt.Color(0, 0, 0));
        lblView.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblView.setForeground(new java.awt.Color(0, 153, 204));
        lblView.setText("VIEW CUSTOMER DATA");
        lblView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblViewMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblViewMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblViewMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout panViewLayout = new javax.swing.GroupLayout(panView);
        panView.setLayout(panViewLayout);
        panViewLayout.setHorizontalGroup(
            panViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblView, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
        );
        panViewLayout.setVerticalGroup(
            panViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panViewLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(panViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblView)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panList.setBackground(new java.awt.Color(0, 0, 102));

        lblList.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblList.setForeground(new java.awt.Color(0, 153, 255));
        lblList.setText("VIEW CUSTOMER LIST");
        lblList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblListMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblListMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblListMouseReleased(evt);
            }
        });
        lblList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblListKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panListLayout = new javax.swing.GroupLayout(panList);
        panList.setLayout(panListLayout);
        panListLayout.setHorizontalGroup(
            panListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblList)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panListLayout.setVerticalGroup(
            panListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panListLayout.createSequentialGroup()
                .addComponent(lblList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panUsage.setBackground(new java.awt.Color(0, 0, 102));

        lblUsage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsage.setForeground(new java.awt.Color(0, 153, 255));
        lblUsage.setText("VIEW WATER USAGE");
        lblUsage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsageMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblUsageMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblUsageMouseReleased(evt);
            }
        });
        lblUsage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblUsageKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panUsageLayout = new javax.swing.GroupLayout(panUsage);
        panUsage.setLayout(panUsageLayout);
        panUsageLayout.setHorizontalGroup(
            panUsageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panUsageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsage, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panUsageLayout.setVerticalGroup(
            panUsageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panUsageLayout.createSequentialGroup()
                .addComponent(lblUsage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panBilling.setBackground(new java.awt.Color(0, 0, 102));

        lblBilling.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBilling.setForeground(new java.awt.Color(0, 153, 255));
        lblBilling.setText("VIEW BILLING");
        lblBilling.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBillingMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBillingMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblBillingMouseReleased(evt);
            }
        });
        lblBilling.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblBillingKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panBillingLayout = new javax.swing.GroupLayout(panBilling);
        panBilling.setLayout(panBillingLayout);
        panBillingLayout.setHorizontalGroup(
            panBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBillingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBilling)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        panBillingLayout.setVerticalGroup(
            panBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBillingLayout.createSequentialGroup()
                .addComponent(lblBilling, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panAdmin.setBackground(new java.awt.Color(0, 0, 102));

        lblAdmin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAdmin.setForeground(new java.awt.Color(0, 153, 255));
        lblAdmin.setText("ADMIN CONTROLS");
        lblAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAdminMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblAdminMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblAdminMouseReleased(evt);
            }
        });
        lblAdmin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblAdminKeyPressed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-setting-23.png"))); // NOI18N

        javax.swing.GroupLayout panAdminLayout = new javax.swing.GroupLayout(panAdmin);
        panAdmin.setLayout(panAdminLayout);
        panAdminLayout.setHorizontalGroup(
            panAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAdmin)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        panAdminLayout.setVerticalGroup(
            panAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panAdminLayout.createSequentialGroup()
                .addGroup(panAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panAdminLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel13))
                    .addComponent(lblAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panTariff.setBackground(new java.awt.Color(0, 0, 102));

        lblTarrif.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTarrif.setForeground(new java.awt.Color(0, 153, 255));
        lblTarrif.setText("VIEW TARIFF");
        lblTarrif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTarrifMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblTarrifMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblTarrifMouseReleased(evt);
            }
        });
        lblTarrif.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblTarrifKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panTariffLayout = new javax.swing.GroupLayout(panTariff);
        panTariff.setLayout(panTariffLayout);
        panTariffLayout.setHorizontalGroup(
            panTariffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTariffLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTarrif)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        panTariffLayout.setVerticalGroup(
            panTariffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panTariffLayout.createSequentialGroup()
                .addComponent(lblTarrif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panPayment.setBackground(new java.awt.Color(0, 0, 102));

        lblPayment.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPayment.setForeground(new java.awt.Color(0, 153, 255));
        lblPayment.setText("VIEW PAYMENT");
        lblPayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPaymentMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblPaymentMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblPaymentMouseReleased(evt);
            }
        });
        lblPayment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblPaymentKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panPaymentLayout = new javax.swing.GroupLayout(panPayment);
        panPayment.setLayout(panPaymentLayout);
        panPaymentLayout.setHorizontalGroup(
            panPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPaymentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        panPaymentLayout.setVerticalGroup(
            panPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPaymentLayout.createSequentialGroup()
                .addComponent(lblPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panMeter.setBackground(new java.awt.Color(0, 0, 102));

        lblMeter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMeter.setForeground(new java.awt.Color(0, 153, 255));
        lblMeter.setText("VIEW WATER METER");
        lblMeter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMeterMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMeterMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblMeterMouseReleased(evt);
            }
        });
        lblMeter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblMeterKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panMeterLayout = new javax.swing.GroupLayout(panMeter);
        panMeter.setLayout(panMeterLayout);
        panMeterLayout.setHorizontalGroup(
            panMeterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMeterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMeter, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panMeterLayout.setVerticalGroup(
            panMeterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panMeterLayout.createSequentialGroup()
                .addComponent(lblMeter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(panList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(panUsage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panBilling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(panTariff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(panPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(panMeter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(panAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)))
                        .addGap(48, 48, 48))))
            .addComponent(panHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(47, 47, 47)
                .addComponent(panHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(panView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panList, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panUsage, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(panMeter, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panBilling, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panTariff, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 300, 710));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 204));
        jLabel3.setText("CUSTOMER BILL");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, -1, -1));

        billingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BILLINGID", "BILLING_DATE", "TOTAL_AMOUNT", "PAYMENT_STATUS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(billingTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 1010, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        // TODO add your handling code here:
        new Home_Tab().setVisible(true);
    }//GEN-LAST:event_lblHomeMouseClicked

    private void lblCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustomerMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lblCustomerMouseClicked

    private void lblHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMousePressed
        // TODO add your handling code here:
        panHome.setBackground(clickedcolor);
    }//GEN-LAST:event_lblHomeMousePressed

    private void lblHomeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseReleased
        // TODO add your handling code here:
         panHome.setBackground(defaultcolor);
    }//GEN-LAST:event_lblHomeMouseReleased

    private void lblCustomerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustomerMousePressed
        // TODO add your handling code here:
        panCustomer.setBackground(clickedcolor);
    }//GEN-LAST:event_lblCustomerMousePressed

    private void lblCustomerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustomerMouseReleased
        // TODO add your handling code here:
         panCustomer.setBackground(defaultcolor);
    }//GEN-LAST:event_lblCustomerMouseReleased

    private void lblViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewMouseClicked
        // TODO add your handling code here:
        new subButtons().setVisible(true);
    }//GEN-LAST:event_lblViewMouseClicked

    private void lblViewMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewMousePressed
        // TODO add your handling code here:
        panView.setBackground(white);
    }//GEN-LAST:event_lblViewMousePressed

    private void lblViewMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewMouseReleased
        // TODO add your handling code here:
        panView.setBackground(defaultcolor);
    }//GEN-LAST:event_lblViewMouseReleased

    private void lblListKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblListKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblListKeyPressed

    private void lblListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblListMouseClicked
        // TODO add your handling code here:
        new viewCustList().setVisible(true);
    }//GEN-LAST:event_lblListMouseClicked

    private void lblListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblListMousePressed
        // TODO add your handling code here:
        panList.setBackground(white);
    }//GEN-LAST:event_lblListMousePressed

    private void lblListMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblListMouseReleased
        // TODO add your handling code here:
        panList.setBackground(defaultcolor);
    }//GEN-LAST:event_lblListMouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lblUsageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsageMouseClicked
        // TODO add your handling code here:
        new viewCustUsage().setVisible(true);
    }//GEN-LAST:event_lblUsageMouseClicked

    private void lblUsageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsageMousePressed
        // TODO add your handling code here:
        panUsage.setBackground(white);
    }//GEN-LAST:event_lblUsageMousePressed

    private void lblUsageMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsageMouseReleased
        // TODO add your handling code here:
        panUsage.setBackground(defaultcolor);
    }//GEN-LAST:event_lblUsageMouseReleased

    private void lblUsageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblUsageKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUsageKeyPressed

    private void lblBillingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBillingMouseClicked
        // TODO add your handling code here:
        new viewCustBilling().setVisible(true);
    }//GEN-LAST:event_lblBillingMouseClicked

    private void lblBillingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBillingMousePressed
        // TODO add your handling code here:
        panBilling.setBackground(white);
    }//GEN-LAST:event_lblBillingMousePressed

    private void lblBillingMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBillingMouseReleased
        // TODO add your handling code here:
        panBilling.setBackground(white);
    }//GEN-LAST:event_lblBillingMouseReleased

    private void lblBillingKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblBillingKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBillingKeyPressed

    private void lblAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdminMouseClicked
        // TODO add your handling code here:
        new adminButton().setVisible(true);
    }//GEN-LAST:event_lblAdminMouseClicked

    private void lblAdminMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdminMousePressed
        // TODO add your handling code here:
        panAdmin.setBackground(white);
    }//GEN-LAST:event_lblAdminMousePressed

    private void lblAdminMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdminMouseReleased
        // TODO add your handling code here:
        panAdmin.setBackground(defaultcolor);
    }//GEN-LAST:event_lblAdminMouseReleased

    private void lblAdminKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblAdminKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAdminKeyPressed

    private void lblTarrifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTarrifMouseClicked
        // TODO add your handling code here:
        new viewCustTariff().setVisible(true);
    }//GEN-LAST:event_lblTarrifMouseClicked

    private void lblTarrifMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTarrifMousePressed
        // TODO add your handling code here:
        panTariff.setBackground(white);
    }//GEN-LAST:event_lblTarrifMousePressed

    private void lblTarrifMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTarrifMouseReleased
        // TODO add your handling code here:
        panTariff.setBackground(defaultcolor);
    }//GEN-LAST:event_lblTarrifMouseReleased

    private void lblTarrifKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblTarrifKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTarrifKeyPressed

    private void lblPaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPaymentMouseClicked
        // TODO add your handling code here:
        new viewCustPayment().setVisible(true);
    }//GEN-LAST:event_lblPaymentMouseClicked

    private void lblPaymentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPaymentMousePressed
        // TODO add your handling code here:
        panPayment.setBackground(white);
    }//GEN-LAST:event_lblPaymentMousePressed

    private void lblPaymentMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPaymentMouseReleased
        // TODO add your handling code here:
        panPayment.setBackground(defaultcolor);
    }//GEN-LAST:event_lblPaymentMouseReleased

    private void lblPaymentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblPaymentKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblPaymentKeyPressed

    private void lblMeterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMeterMouseClicked
        // TODO add your handling code here:
        new viewCustMeter().setVisible(true);
    }//GEN-LAST:event_lblMeterMouseClicked

    private void lblMeterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMeterMousePressed
        // TODO add your handling code here:
        panMeter.setBackground(white);
    }//GEN-LAST:event_lblMeterMousePressed

    private void lblMeterMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMeterMouseReleased
        // TODO add your handling code here:
        panMeter.setBackground(defaultcolor);
    }//GEN-LAST:event_lblMeterMouseReleased

    private void lblMeterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblMeterKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMeterKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewCustBilling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewCustBilling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewCustBilling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewCustBilling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewCustBilling().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable billingTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblBilling;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblList;
    private javax.swing.JLabel lblMeter;
    private javax.swing.JLabel lblPayment;
    private javax.swing.JLabel lblTarrif;
    private javax.swing.JLabel lblUsage;
    private javax.swing.JLabel lblView;
    private javax.swing.JPanel panAdmin;
    private javax.swing.JPanel panBilling;
    private javax.swing.JPanel panCustomer;
    private javax.swing.JPanel panHome;
    private javax.swing.JPanel panList;
    private javax.swing.JPanel panMeter;
    private javax.swing.JPanel panPayment;
    private javax.swing.JPanel panTariff;
    private javax.swing.JPanel panUsage;
    private javax.swing.JPanel panView;
    // End of variables declaration//GEN-END:variables
}
